package com.B2B.extra;

public enum RejectionCause
{
    DAILY_LIMIT_REACHED,
    NOT_ENOUGH_FUNDS,
    MONTH_LIMIT_REACHED,
    USER_NOT_FOUND,
    USER_NOT_ACTIVE,
    CURRENCY_NOT_SUPPORTED,
    GENERAL_REJECTION
}
